version: 2.1
executors:
  exectr:
    docker:
      - image: silverlinings89/cpp_build_environment:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup gtest child repo
          command: |
            cd third_party
            git submodule init
            git submodule update 
      - run:
          name: Setup cmake and build artifacts
          command: |
            cmake .
            make
      - persist_to_workspace:
          root: .
          paths: build

  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build/bin
            gtest --gtest_output=xml
      - store_test_results:
          path: build/bin/test_detail.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - build #(11)
      - test: #(12)
          requires:
            - build